spring:
  redis:
    # Redis服务器地址
    host: 192.168.243.128
    # Redis服务器端口
    port: 6379
    # Redis服务器端口
    password: jwj422123
    # Redis服务器端口
    database: 0
    # 连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，单位毫秒，默认-1ms
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5




